### ISSUE TITLE
[DOCS] : Link License and Contributing.md to ReadMe

### ISSUE THREAD

**Issue by shashankbhatgs** [nanlabs/infra-reference#13]
## Description
**Is your feature request related to a problem? Please describe.**

- Improving the docs by adding the LICENSE and contributing.md links to the ReadMe file.

**Describe the solution you'd like**

- I would like to add the links of LICENSE and Contributing.md at the bottom of the readme file so as to make the readme more structured.

**Comment by shashankbhatgs** [comment]
also i would like to work on this if you think this is a valid issue. @ulises-jeremias

**Comment by ulises-jeremias** [comment]
Sure!
