### ISSUE TITLE
Sample buildpacking a simple python app

### ISSUE THREAD

**Issue by di3go-martinez** [nanlabs/infra-reference#31]
Write a sample app in Python, get an OCI image created without a Dockerfile, but using pack utility from Buildpacks

**Comment by di3go-martinez** [comment]
@ulises-jeremias let me know if it works for you

**Comment by ulises-jeremias** [comment]
sounds great! feel free to create a new dir called `examples/buildpack/` on your PR

**Comment by di3go-martinez** [comment]
great! hands-on it
