### ISSUE TITLE
examples/sls: Add basic http lambda with middy

### ISSUE THREAD

**Issue by ulises-jeremias** [nanlabs/infra-reference#9]
Create a new example at `examples/serverless/serverless-middy` with a basic lambda with an http based trigger.
You can use the example [`serverless-appsync-nodejs`](https://github.com/nanlabs/infra-reference/tree/main/examples/serverless/serverless-appsync-nodejs) as an example on how to setup a sls + typescript project.

The example should use the library [middy](https://middy.js.org/) with a basic middleware.

**Comment by darioscrivano** [comment]
@ulises-jeremias te parece si agarro este?

**Comment by ulises-jeremias** [comment]
Sure!
